### ISSUE TITLE
Missing record types

### ISSUE THREAD

**Issue by pqvst** [lvauvillier/dji-log-parser#7]
While processing some M3E flight logs, I found the following record types to be unhandled. I have noted the `FlightRecordDataType` from the DJI `FlightRecordParsingLib` repo.

I also noticed that the output I get is missing some key data (e.g. RC, BATTERY, WEATHER), but they are present in the output I get from PhantomHelp.

- 10: `ShowWarningFlightRecordDataType`
- 17: `VisionGroupDataType`
- 45: `RTKDifferenceDataType`
- 48: `AgricultureGroundStationPushData`
- 55: `npzeXkozKlNHPjUQ`
- 57: `GOAirLinkDataField`
- 62: `RemoteControllerDisplayField`
- 63: `FlightControllerCommonOSDField`

I believe 55 might contain battery information, but I haven't had any luck decoding it.

**Comment by lvauvillier** [comment]
Hi @pqvst, thanks for reporting this. I simply don't add those records because I can't find some samples to validate if all is okay. If you can share some flight records of M3E, I will be able to add them.

**Comment by pqvst** [comment]
Thanks @lvauvillier! Happy to provide you with some sample data. Any way I can share it with you privately?

**Comment by lvauvillier** [comment]
Of course, I just sent you an email using the contact email from your blog.

**Comment by lvauvillier** [comment]
Hi @pqvst, based on your log files i was able to fix some missing fields to get cell voltages (in `SmartBatteryGroup`).

I spend some time to understand why some info were missing from PhantomHelp and here is my findings:

**BATTERY.[field]:**
Information can be retrieved from several locations. I think they gather data from multiple locations to build the BATTERY* fields:
- `Record::SmartBattery`
- `Record::SmartBatteryGroup` (now fixed, you can get all cell voltages :))
- `Record::CenterBattery`

**RC.[field]:**
I guess the use `Record::RC` but i can't find any RC records from your logs (maybe due to waypoint flight mode). I can't find how they are able to extract some data (aileron, elevator, throttle, rudder have different values over time)
The `Record:OFDM` can be used to get RC.downlinkSignal and RC.uplinkSignal values.

**WEATHER.[field]:**
Not sure where this data comes from or if it's retrieved from the logs. Maybe they enhance the data using an external API (like Airdata does).

And here is the dataframe status:

* 10: ShowWarningFlightRecordDataType
=> already parsed in `Record::AppWarn`
* 17: VisionGroupDataType
=> i need more time to understand the logic from `FlightRecordParsingLib` but feasible 
* 45: RTKDifferenceDataType
=> no data layout info in `FlightRecordParsingLib`
* 48: AgricultureGroundStationPushData
=> no data layout info in `FlightRecordParsingLib`
* 55: npzeXkozKlNHPjUQ
* 57: GOAirLinkDataField
=> no data layout info in `FlightRecordParsingLib`
* 62: RemoteControllerDisplayField
=> no data layout info in `FlightRecordParsingLib`
* 63: FlightControllerCommonOSDField
=> feasible

**Comment by pqvst** [comment]
@lvauvillier I thought maybe `RemoteControllerDisplayField` mapped to `dji_fc_osd_push` (if I trace the DJI code), which I guess might contain the RC data, but I'm not 100% sure.

**Comment by lvauvillier** [comment]
There is only an enum value of `RemoteControllerDisplayField`. There is no other reference in the DJI code.

By the way, I also ran the official parsing library on your logs and there is no RC data...

From `dji_fc_osd_push`, we can retrieve the quad orientation (pitch, yaw, roll), but not the RC stick position.

**Comment by lvauvillier** [comment]
I was finally able to decode RC data from RemoteControllerDisplayField.

WEATHER data from phantomhelp is not part of the log.
